# Generated by Django 5.0.5 on 2024-05-13 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=10, unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='Image')),
                ('publish', models.DateTimeField(default=datetime.datetime(2024, 5, 13, 8, 12, 50, 624095, tzinfo=datetime.timezone.utc))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('p', 'published'), ('d', 'draft')], max_length=1)),
            ],
        ),
    ]
